### ISSUE TITLE
library have tons of bugs, maybe update that or specify that project is outdated

### ISSUE THREAD

**Issue by maciekpaprocki** [schmidsi/jquery-object-fit#7]

**Comment by 0x80** [comment]
Yes I agree. I the `prefix` variable in the `testForObjectFit` function is even undefined?

**Comment by schmidsi** [comment]
Hi, unfortunately, I do not find time to maintain this repository. I updated the readme. So if anybody wants to jump in, I am happy to give write-permissions.

@sophiedeziel @steveworkman @yukulele ?

**Comment by yukulele** [comment]
You can use this polyfill https://github.com/bfred-it/object-fit-images/

(could be suggested as alternative in readme)

**Comment by steveworkman** [comment]
Sorry, I don't have time to maintain my own fork either, let alone this one!

**Comment by schmidsi** [comment]
I updated the readme with the link to https://github.com/bfred-it/object-fit-images/. That should help. Thanks for poking.
